sudo: false
language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notification:
  email: false
script:
  - npm run validate
after_success:
  - npm run report-coverage
